---
title: "Project 02"
author: "Arushi Arora / Peter Fernandez"
date: "10/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(dplyr)
library(ggplot2)
library(RMySQL)
```


#### Import and Rename Variables in Federal Spending Data

```{r}
# Read the csv file from GitHub with the table data
# Rename the columns to make them easier to use
df_csv <- read.csv("https://raw.githubusercontent.com/Araisedtotwo/Project02/main/DataUSACart.csv", header = TRUE) %>%
  as_tibble() %>%
  rename(id = ID.Geography , 
         agencyid= ID.Agency ,
         amount = Obligation.Amount..2017.) %>%
  print()
# 6557 obs and 5 vars
```

#### Creating AWS MySQL Connection & Reading Data from MySQL
```{r,warning=FALSE}
mysqlconnection = dbConnect(MySQL(), user='root', password='xxxx', dbname ='federal_spending',host='aws-movie-rating.cc7r4c0owv8u.us-east-1.rds.amazonaws.com')
result = dbSendQuery(mysqlconnection,"SELECT `ID Geography` AS id,`Geography`,`ID Agency`AS agencyid ,`Agency`,`Obligation Amount (2017)` AS amount FROM federal_spending.fedspend")
df=fetch(result,n= -1)
head(df)
```


#### Clean data

```{r}
# Remove amounts that are in -ve
df1 <- df %>%
  filter(amount > 0)
head(df1)
# 6158 obs and 5 vars
```

#### Let us sort data by spending amount and look at the summary of all variables
```{r}
df2 <- df1 %>%
  arrange(amount)
summary(df2)
```

#### Calculate the overall spending by State 

```{r,warning=FALSE}
state_spending <- df2 %>% group_by(Geography) %>% summarize(sum_state = sum(amount)) %>%
  arrange(desc(sum_state, Geography))
head(state_spending)
# California has the highest Federal Spending at $186,831,546,017

```

#### Plotting 5 highest spending states
```{r}
df7 <- state_spending %>% top_n(5) 

plot1 <- ggplot(df7, aes(Geography,sum_state )) + 
  geom_bar(aes(fill = Geography), position = "dodge", stat = "identity") + 
  geom_text(aes(label = sum_state), vjust = -.3) +
  ylab("Amount Spent") +
  ggtitle("5 highest spending states")

plot1
```


#### Calculate the overall spending by Agency 

```{r,warning=FALSE}
agency_spending <- df2 %>% group_by(Agency) %>% summarize(sum_agency = sum(amount)) %>%
  arrange(desc(sum_agency, Agency))
head(agency_spending)
# Centers for Medicare and Medicaid Services at $687,665,667,131 is the highest spending agency
```

#### Plotting 5 lowest spending agencies
```{r}
df8 <- agency_spending %>% top_n(-5) 

plot2 <- ggplot(df8, aes(Agency,sum_agency/1000 )) + 
  geom_bar(aes(fill = Agency), position = "dodge", stat = "identity") + theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())  +
  geom_text(aes(label = sum_agency*1000), vjust = -.3) +
  ylab("Amount Spent") +
  ggtitle("5 lowest spending agencies")

plot2
```
